from pathlib import Path
from typing import Any

from .models import Candidate

class HRX:
    candidate: Candidate
    def __init__(self, source: Path | str | dict[str, Any] | Candidate) -> None: ...
    @classmethod
    def from_path(cls, path: Path | str) -> HRX: ...
    @classmethod
    def from_json(cls, payload: str) -> HRX: ...
    @classmethod
    def from_dict(cls, payload: dict[str, Any]) -> HRX: ...
    def to_dict(self) -> dict[str, Any]: ...
    def to_json(self, *, indent: int = 2) -> str: ...
    def validate_against_schema(self, schema: dict[str, Any] | str | Path) -> None: ...
