from typing import Any

class HrxError(Exception):
    details: Any | None
    def __init__(self, message: str, *, details: Any | None = None) -> None: ...

class HrxFileError(HrxError): ...
class HrxParseError(HrxError): ...
class HrxValidationError(HrxError): ...
class HrxSchemaError(HrxError): ...
class HrxVersionError(HrxError): ...
