"""
This type stub file was generated by pyright.
"""

RECAPTCHA_VERIFY_SERVER_DEFAULT = ...
RECAPTCHA_ERROR_CODES = ...
__all__ = ["Recaptcha"]
class Recaptcha:
    """Validates a ReCaptcha.

    Verification is skipped and the field is considered valid whenever
    ``current_app.testing`` is ``True`` or ``RECAPTCHA_ENABLED`` is
    ``False``, so tests and offline development don't need a real
    reCAPTCHA token.

    .. versionchanged:: 1.3.0
        Verification is also skipped when ``RECAPTCHA_ENABLED`` is
        ``False``.
    """
    def __init__(self, message=...) -> None:
        ...
    
    def __call__(self, form, field): # -> Literal[True] | None:
        ...
    


