"""
This type stub file was generated by pyright.
"""

RECAPTCHA_SCRIPT_DEFAULT = ...
RECAPTCHA_DIV_CLASS_DEFAULT = ...
__all__ = ["RecaptchaWidget"]
class RecaptchaWidget:
    def recaptcha_html(self, public_key, nonce=..., **kwargs): # -> Markup:
        ...
    
    def __call__(self, field, error=..., **kwargs): # -> Markup:
        """Returns the recaptcha input HTML."""
        ...
    


